### ISSUE TITLE
Xposed edge doesn't work

### ISSUE THREAD

**Issue by panda82** [Magisk-Modules-Repo/taichi#2]
Hi.

I have Resurrection remix on Samsung Note3 Android Pie.

I've installed latest module and app of taiChi and compatible version of xposed edge and after reboot it's stuck on boot screen!

Can you help with this? Thanks!

**Comment by tiann** [comment]
@panda82 try this version?
[5.1.9.7.apk.zip](https://github.com/Magisk-Modules-Repo/taichi/files/3097772/5.1.9.7.apk.zip)
