### ISSUE TITLE
Why does config.sh still exist?

### ISSUE THREAD

**Issue by topjohnwu** [Magisk-Modules-Repo/taichi#4]
你好，我發現你更新到新的 module format 了，不過好奇問一下，為什麼 `config.sh` 仍然在 repo 中呢？我的偵測腳本目前看到 `config.sh` 的話誤判為舊版 format (沒有更好的辦法來偵測舊版與新版的差異了...真是抱歉哈哈)，會導致你的 module 在 5/1 的時候被錯誤地刪除掉。

特此告知！

**Comment by tiann** [comment]
已经更新啦。
之前我以为只要把 `config.sh` 保留就能兼容老版本，看来是我多虑了 :)

谢谢提醒！
