### ISSUE TITLE
No modules I try work?

### ISSUE THREAD

**Issue by steve51184** [Magisk-Modules-Repo/taichi#5]
I have a OnePlus 5 on Oreo 8.1 running the latest magisk module v4.9.1 with the latest v5.1.10 of the app yet no matter what xposed module I install I'm just left with 'module not supported? 

https://i.imgur.com/QvHFEnu.jpg

**Comment by tiann** [comment]
I will try these:

1. [Xposed-DataUsage](https://repo.xposed.info/module/io.github.francoiscampbell.xposeddatausage)
2. [Burnt Toast](https://repo.xposed.info/module/me.rapperskull.burnttoastrevived)
3. [Boot Manager](https://repo.xposed.info/module/de.defim.apk.bootmanager)
4. [CustomShare](https://repo.xposed.info/module/de.defim.apk.customshare)
5. [NotifyClean](https://repo.xposed.info/module/de.defim.apk.notifyclean)


BubbleUpnp seems a known issue: https://github.com/taichi-framework/TaiChi/issues/346 

And Minminguard: https://github.com/taichi-framework/TaiChi/issues/28

Here is the supported list : https://taichi.cool/module/module.html

**Comment by tiann** [comment]
Please use the lastest taichi and try again, some should be fixed.
