### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by oxr463** [Magisk-Modules-Repo/taichi#6]
This project doesn't contain a license.

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

Source: https://choosealicense.com/no-permission

I'd recommend GPL-3.0-or-later, as that is the license for Magisk.

See also: https://github.com/taichi-framework/TaiChi/issues

**Comment by tiann** [comment]
https://github.com/taichi-framework/TaiChi/issues/892
